name: Generator

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        default: 'app'

env:
  PROJECT: ${{github.event.inputs.project}}
  NODE_VERSION: '14.1'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commit:
    name: Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-node-
      - run: npm ci
      - name: Id
        run: node scripts/id.js
      - name: Generator
        run: ./scripts/generator.sh

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update Translations
          branch: translations/${{env.PROJECT}}
          delete-branch: true
          title: Update translations for ${{env.PROJECT}}
          body: |
            Update report
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: update-translations
          draft: true

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
