name: Generator

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        default: 'app'
      branch:
        description: 'Branch'
        required: true
        default: 'master'

env:
  PROJECT: ${{github.event.inputs.project}}
  BASE_BRANCH: ${{github.event.inputs.branch}}
  NODE_VERSION: '14.1'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commit:
    name: Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-node-
      - run: npm ci
      - name: Id
        run: node scripts/id.js
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: translations/${{env.PROJECT}}/${{env.RANDOM_ID}}
      - name: Fetch
        run: git fetch
      - uses: actions/checkout@v2
        with:
          ref: translations/${{env.PROJECT}}/${{env.RANDOM_ID}}
      - name: Generate
        run: scripts/generator.sh
# You can make whatever type of change to the repo...
      - run: echo "123" > ./pathToRepo/file.txt
      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: Create new file
          ref: translations/${{env.PROJECT}}/${{env.RANDOM_ID}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: translations/${{env.PROJECT}}/${{env.RANDOM_ID}}
          title: ${{env.PROJECT}} Translations Update
          base: ${{env.BASE_BRANCH}}
          draft: true
